### ISSUE TITLE
[users] nick_name field ==> last_name field.

### ISSUE THREAD

**Issue by osamamhd** [IndieCoder-org/api#6]
when the user registers a new account the nickname entry will fill the nickname field and the last name field.

**Comment by siddhartharao17** [comment]
Hello! I'm not new to open source contributions but my contributions have always been non-code. I'm trying to get better at code contributions and would like to take up this issue. If I could also get some help/guidance on the way, I would be grateful.

**Comment by osamamhd** [comment]
I didn't do many open source contributions myself, but I am thankful for your contribution.
And I am happy to help.

**Comment by siddhartharao17** [comment]
ok perfect! I appreciate the response. I'm trying to understand the issue description better. I guess I understand the objective here. What I'm trying to understand is where in the code base I should be looking? When a user fills in all the fields on this login form.

![image](https://user-images.githubusercontent.com/8169998/129140634-57c9ec8f-3f51-4441-a4e3-9a0178ff647a.png)

it's hitting the /register end point. So, I need to be looking at a code that would handle that request right?

**Comment by osamamhd** [comment]
I revied the code, but I don't know where the bug is, so I made this issue here and https://github.com/IndieCoder-org/web/issues/9
So you cna look at the code perhaps I am missing something, thanks.

**Comment by siddhartharao17** [comment]
Just submitted a pull request, let me know if the changes are correct.

**Comment by osamamhd** [comment]
when you submitted this pr, I noticed the fix is so simple. [FIXED]
check line 22.
check it:
https://github.com/IndieCoder-org/api/pull/13

**Comment by siddhartharao17** [comment]
Thanks! Glad I was able to help.

**Comment by osamamhd** [comment]
Any time...
